language: bash

# for secret experimental features ;)
sudo: 9000

env:
  - VERSION=18 VARIANT=
  - VERSION=18 VARIANT=esl
  - VERSION=18 VARIANT=c6-esl
  - VERSION=17 VARIANT=
  - VERSION=R16 VARIANT=
  - VERSION=R15 VARIANT=

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - env | sort
  - cd "$VERSION"
  - image="$(awk '$1 == "FROM" { print $2; exit }' onbuild/Dockerfile)${VARIANT:+-$VARIANT}"

script:
  - docker build --pull -t "$image" "${VARIANT:-.}"
  - ~/official-images/test/run.sh "$image"
# the "onbuild" variant has to happen with the base variant because it's FROM it
  - true && [ "$VARIANT" ] || docker build -t "${image}-onbuild" onbuild

after_script:
  - docker images
