language: bash
services: docker

env:
  global:
  - REBAR3_VERSION=3.12.0
  - REBAR3_DOWNLOAD_SHA256=8ac45498f03e293bc6342ec431888f9a81a4fb9e1177a69965238d127c00a79e
  matrix:
  - DIR=master
  - DIR=master VARIANT=alpine
  - DIR=22
  - DIR=22 VARIANT=slim
  - DIR=22 VARIANT=alpine
  - DIR=21
  - DIR=21 VARIANT=slim
  - DIR=21 VARIANT=alpine
  - DIR=20
  - DIR=20 VARIANT=slim
  - DIR=20 VARIANT=alpine
  - DIR=19
  - DIR=19 VARIANT=slim

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - cd "$DIR"
  - eval $(awk '/OTP_VERSION=/ { sub(/@/, "-", $2); print $2; exit }' ${VARIANT:-.}/Dockerfile)
  - image="erlang:${OTP_VERSION}${VARIANT:+-$VARIANT}"

script:
    - docker build --build-arg REBAR3_VERSION=$REBAR3_VERSION --build-arg REBAR3_DOWNLOAD_SHA256=$REBAR3_DOWNLOAD_SHA256 --pull -t "$image" "${VARIANT:-.}"
    - ~/official-images/test/run.sh "$image"

after_script:
  - docker images
